# Generated by Django 4.2.11 on 2025-07-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slide_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
