# Generated by Django 4.2.11 on 2025-07-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_slider_slide_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, help_text='The recommended size is 120x120 pixels.', null=True, upload_to='categories/', verbose_name='category')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished')], default='Published', max_length=20)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, help_text='The recommended size is 120x120 pixels.', null=True, upload_to='subcategories/', verbose_name='subcategory')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished')], default='Published', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='web.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, help_text='The recommended size is 300x300 pixels.', null=True, upload_to='products/', verbose_name='product')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished')], default='Published', max_length=20)),
                ('whatsapp_link', models.URLField(blank=True, help_text='Link to WhatsApp with product details (e.g., https://wa.me/1234567890?text=Product%20Details).', null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryproducts', to='web.subcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
    ]
